# Generated by Django 6.0 on 2025-12-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_manufacturer_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_house',
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication_house',
        ),
    ]
