# Generated by Django 6.0 on 2025-12-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_book_authors_remove_book_publication_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
